platform :ios, '8.0'
use_frameworks!

target 'party-on' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'AFNetworking', '~> 2.0'
    pod 'SVProgressHUD'
    pod 'Synchronized'
end
